# Generated by Django 6.1 on 2026-08-29 12:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wines', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('vintage', models.PositiveIntegerField(blank=True, null=True)),
                ('wine_type', models.CharField(choices=[('red', 'Red'), ('white', 'White'), ('rose', 'Rosé'), ('sparkling', 'Sparkling'), ('dessert', 'Dessert'), ('fortified', 'Fortified')], max_length=20)),
                ('varietal', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('image_url', models.URLField(blank=True)),
                ('external_api_id', models.CharField(blank=True, max_length=255)),
                ('external_source', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wines', to='wines.region')),
                ('winery', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wines', to='wines.winery')),
            ],
        ),
    ]
