# Generated by Django 6.1 on 2026-09-05 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wines', '0002_wine'),
    ]

    operations = [
        migrations.AddField(
            model_name='wine',
            name='acidity',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='wine',
            name='alcohol_content',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='wine',
            name='body',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
